name: stx_flutter_form_bloc
description: Easy Form State Management using BLoC pattern. Separate the Form State and Business Logic from the User Interface.
version: 0.0.2

homepage: https://github.com/VolodymyrSydorko/stx_flutter_form_bloc
repository: https://github.com/VolodymyrSydorko/stx_flutter_form_bloc
documentation: https://github.com/VolodymyrSydorko/stx_flutter_form_bloc

environment:
  sdk: ">=2.16.2 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  stx_form_bloc: ^1.0.2

  flutter_bloc: ^8.0.1

dev_dependencies:
  flutter_lints: ^1.0.4