name: stx_flutter_form_bloc
description: Easy Form State Management using BLoC pattern. Separate the Form State and Business Logic from the User Interface.
version: 3.0.0

homepage: https://github.com/VolodymyrSydorko/stx_flutter_form_bloc
repository: https://github.com/VolodymyrSydorko/stx_flutter_form_bloc
documentation: https://github.com/VolodymyrSydorko/stx_flutter_form_bloc

environment:
  sdk: ">=3.5.0 <4.0.0"
  flutter: ">=3.24.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_bloc: ^9.0.0
  stx_form_bloc: ^4.0.0

dev_dependencies:
  flutter_lints: ^5.0.0